-- ============================================
-- Actualización de tabla VRE_COCURRICULARES
-- Agregar columnas faltantes
-- ============================================

USE pruebasumadmin;

-- Primero, copiar datos de columnas antiguas antes de modificar
UPDATE VRE_COCURRICULARES
SET DESCRIPCION = CONCAT(
    IFNULL(DESCRIPCION, ''),
    IF(RESPONSABLE IS NOT NULL AND RESPONSABLE != '', CONCAT('\n\nResponsable: ', RESPONSABLE), ''),
    IF(CONTACTO IS NOT NULL AND CONTACTO != '', CONCAT('\nContacto: ', CONTACTO), '')
)
WHERE RESPONSABLE IS NOT NULL OR CONTACTO IS NOT NULL;

-- Agregar nuevas columnas a VRE_COCURRICULARES
ALTER TABLE VRE_COCURRICULARES
    ADD COLUMN TIPO VARCHAR(100) AFTER NOMBRE,
    ADD COLUMN OBJETIVO TEXT AFTER DESCRIPCION,
    ADD COLUMN REQUISITOS TEXT AFTER OBJETIVO,
    ADD COLUMN BENEFICIOS TEXT AFTER REQUISITOS,
    ADD COLUMN RESPONSABLE_NOMBRE VARCHAR(200) AFTER BENEFICIOS,
    ADD COLUMN RESPONSABLE_EMAIL VARCHAR(200) AFTER RESPONSABLE_NOMBRE,
    ADD COLUMN RESPONSABLE_TELEFONO VARCHAR(50) AFTER RESPONSABLE_EMAIL,
    ADD COLUMN HORARIOS TEXT AFTER RESPONSABLE_TELEFONO,
    ADD COLUMN UBICACION VARCHAR(300) AFTER HORARIOS,
    ADD COLUMN CUPO_MAXIMO INT AFTER UBICACION;

-- Copiar CATEGORIA a TIPO
UPDATE VRE_COCURRICULARES
SET TIPO = CATEGORIA
WHERE TIPO IS NULL AND CATEGORIA IS NOT NULL;

-- Ahora podemos eliminar las columnas antiguas
ALTER TABLE VRE_COCURRICULARES
    DROP COLUMN CATEGORIA,
    DROP COLUMN RESPONSABLE,
    DROP COLUMN CONTACTO;

SELECT 'Tabla VRE_COCURRICULARES actualizada correctamente' AS mensaje;
