-- ============================================
-- SCRIPT COMPLETO PARA CLUBES Y MINISTERIOS
-- Agrega todas las tablas necesarias
-- ============================================

USE pruebasumadmin;

-- ============================================
-- TABLA VRE_GALERIA (Sistema centralizado de imágenes)
-- ============================================
CREATE TABLE IF NOT EXISTS VRE_GALERIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MODULO VARCHAR(50) NOT NULL COMMENT 'clubes, ministerios, deportes, ligas, eventos, banners',
    ID_REGISTRO INT NOT NULL COMMENT 'ID del registro en la tabla correspondiente',
    TITULO VARCHAR(200),
    URL_IMAGEN VARCHAR(500) NOT NULL,
    TIPO ENUM('principal', 'galeria', 'banner', 'evento') DEFAULT 'galeria',
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    SUBIDO_POR INT,
    FECHA_SUBIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SUBIDO_POR) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_modulo_registro (MODULO, ID_REGISTRO),
    INDEX idx_tipo (TIPO)
) ENGINE = INNODB;

-- ============================================
-- TABLA VRE_DIRECTIVA_CLUBES
-- ============================================
CREATE TABLE IF NOT EXISTS VRE_DIRECTIVA_CLUBES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLUB INT NOT NULL,
    DIRECTOR_NOMBRE VARCHAR(200),
    DIRECTOR_EMAIL VARCHAR(200),
    DIRECTOR_TELEFONO VARCHAR(50),
    DIRECTOR_FOTO VARCHAR(500),
    SUBDIRECTOR_NOMBRE VARCHAR(200),
    SUBDIRECTOR_EMAIL VARCHAR(200),
    SUBDIRECTOR_TELEFONO VARCHAR(50),
    SUBDIRECTOR_FOTO VARCHAR(500),
    SECRETARIO_NOMBRE VARCHAR(200),
    SECRETARIO_EMAIL VARCHAR(200),
    SECRETARIO_TELEFONO VARCHAR(50),
    SECRETARIO_FOTO VARCHAR(500),
    TESORERO_NOMBRE VARCHAR(200),
    TESORERO_EMAIL VARCHAR(200),
    TESORERO_TELEFONO VARCHAR(50),
    TESORERO_FOTO VARCHAR(500),
    CAPELLAN_NOMBRE VARCHAR(200),
    CAPELLAN_EMAIL VARCHAR(200),
    CAPELLAN_TELEFONO VARCHAR(50),
    CAPELLAN_FOTO VARCHAR(500),
    CONSEJERO_GENERAL_NOMBRE VARCHAR(200),
    CONSEJERO_GENERAL_EMAIL VARCHAR(200),
    CONSEJERO_GENERAL_TELEFONO VARCHAR(50),
    CONSEJERO_GENERAL_FOTO VARCHAR(500),
    LOGISTICA_NOMBRE VARCHAR(200),
    LOGISTICA_EMAIL VARCHAR(200),
    LOGISTICA_TELEFONO VARCHAR(50),
    LOGISTICA_FOTO VARCHAR(500),
    MEDIA_NOMBRE VARCHAR(200),
    MEDIA_EMAIL VARCHAR(200),
    MEDIA_TELEFONO VARCHAR(50),
    MEDIA_FOTO VARCHAR(500),
    ESTADO ENUM('activo','inactivo') DEFAULT 'activo',
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLUB) REFERENCES VRE_CLUBES(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- TABLA VRE_DIRECTIVA_MINISTERIOS
-- ============================================
CREATE TABLE IF NOT EXISTS VRE_DIRECTIVA_MINISTERIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_MINISTERIO INT NOT NULL,
    DIRECTOR_NOMBRE VARCHAR(200),
    DIRECTOR_EMAIL VARCHAR(200),
    DIRECTOR_TELEFONO VARCHAR(50),
    DIRECTOR_FOTO VARCHAR(500),
    SUBDIRECTOR_NOMBRE VARCHAR(200),
    SUBDIRECTOR_EMAIL VARCHAR(200),
    SUBDIRECTOR_TELEFONO VARCHAR(50),
    SUBDIRECTOR_FOTO VARCHAR(500),
    SECRETARIO_NOMBRE VARCHAR(200),
    SECRETARIO_EMAIL VARCHAR(200),
    SECRETARIO_TELEFONO VARCHAR(50),
    SECRETARIO_FOTO VARCHAR(500),
    TESORERO_NOMBRE VARCHAR(200),
    TESORERO_EMAIL VARCHAR(200),
    TESORERO_TELEFONO VARCHAR(50),
    TESORERO_FOTO VARCHAR(500),
    CAPELLAN_NOMBRE VARCHAR(200),
    CAPELLAN_EMAIL VARCHAR(200),
    CAPELLAN_TELEFONO VARCHAR(50),
    CAPELLAN_FOTO VARCHAR(500),
    CONSEJERO_GENERAL_NOMBRE VARCHAR(200),
    CONSEJERO_GENERAL_EMAIL VARCHAR(200),
    CONSEJERO_GENERAL_TELEFONO VARCHAR(50),
    CONSEJERO_GENERAL_FOTO VARCHAR(500),
    LOGISTICA_NOMBRE VARCHAR(200),
    LOGISTICA_EMAIL VARCHAR(200),
    LOGISTICA_TELEFONO VARCHAR(50),
    LOGISTICA_FOTO VARCHAR(500),
    MEDIA_NOMBRE VARCHAR(200),
    MEDIA_EMAIL VARCHAR(200),
    MEDIA_TELEFONO VARCHAR(50),
    MEDIA_FOTO VARCHAR(500),
    ESTADO ENUM('activo','inactivo') DEFAULT 'activo',
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_MINISTERIO) REFERENCES VRE_MINISTERIOS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- VERIFICACIÓN
-- ============================================
SELECT 'Todas las tablas necesarias han sido creadas correctamente' AS STATUS;

-- Verificar tablas creadas
SELECT 'Tablas verificadas:' AS INFO;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'pruebasumadmin'
AND TABLE_NAME IN ('VRE_GALERIA', 'VRE_DIRECTIVA_CLUBES', 'VRE_DIRECTIVA_MINISTERIOS')
ORDER BY TABLE_NAME;
