-- ============================================
-- SCRIPT PARA AGREGAR TABLAS FALTANTES
-- Este script agrega las tablas que faltan en SISTEMA_VRE_COMPLETO.sql
-- pero que están en db.sql
-- ============================================

USE pruebasumadmin;

-- ============================================
-- MÓDULO 1: ANUARIOS
-- ============================================

CREATE TABLE IF NOT EXISTS VRE_ANUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL,
    ANIO YEAR NOT NULL,
    DESCRIPCION TEXT,
    DECADA INT,
    ES_CONMEMORATIVO ENUM('S','N') DEFAULT 'N',
    RAZON_CONMEMORATIVA VARCHAR(300),
    IMAGEN_PORTADA VARCHAR(500),
    PDF_URL VARCHAR(500),
    TOTAL_PAGINAS INT DEFAULT 0,
    FOTOGRAFOS TEXT,
    CONTRIBUYENTES TEXT,
    LIKES INT DEFAULT 0,
    VISTAS INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO_CREADOR INT,
    FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_anio (ANIO),
    INDEX idx_decada (DECADA)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VRE_ANUARIOS_FOTOS_ESTUDIANTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ANUARIO INT,
    MATRICULA VARCHAR(50) NOT NULL,
    NOMBRE_ESTUDIANTE VARCHAR(200),
    CARRERA VARCHAR(100),
    FACULTAD VARCHAR(100),
    FOTO_URL VARCHAR(500),
    ANIO YEAR,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FOREIGN KEY (ID_ANUARIO) REFERENCES VRE_ANUARIOS(ID) ON DELETE CASCADE,
    INDEX idx_matricula (MATRICULA)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VRE_ANUARIOS_LIKES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ANUARIO INT NOT NULL,
    ID_USUARIO INT,
    MATRICULA VARCHAR(50),
    IP VARCHAR(50),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ANUARIO) REFERENCES VRE_ANUARIOS(ID) ON DELETE CASCADE,
    UNIQUE KEY unique_like (ID_ANUARIO, ID_USUARIO, MATRICULA, IP)
) ENGINE=INNODB;

-- ============================================
-- MÓDULO 2: PULSO UM
-- ============================================

CREATE TABLE IF NOT EXISTS VRE_PULSO_EQUIPOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    ANIO YEAR NOT NULL,
    PERIODO VARCHAR(50),
    FOTO_URL VARCHAR(500),
    BIO TEXT,
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VRE_ENTREGA_ANUARIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ANIO YEAR UNIQUE NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_ENTREGA DATE,
    HORA_INICIO TIME,
    HORA_FIN TIME,
    LUGAR VARCHAR(200),
    INSTRUCCIONES TEXT,
    REQUISITOS TEXT,
    CONTACTO VARCHAR(200),
    IMAGEN_URL VARCHAR(500),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- ============================================
-- MÓDULO 3: FEDERACIÓN ESTUDIANTIL
-- ============================================

CREATE TABLE IF NOT EXISTS VRE_FEDERACION_MIEMBROS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    PUESTO VARCHAR(100) NOT NULL,
    ANIO YEAR NOT NULL,
    MATRICULA VARCHAR(50),
    CARRERA VARCHAR(100),
    FOTO_URL VARCHAR(500),
    BIO TEXT,
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(20),
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VRE_FEDERACION_INFO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200),
    CONTENIDO_QUE_ES TEXT,
    CONTENIDO_ELECCION TEXT,
    CONTENIDO_ACTIVIDADES TEXT,
    CONTENIDO_PARA_QUE_SIRVE TEXT,
    VIDEO_URL VARCHAR(500),
    IMAGEN_PRINCIPAL VARCHAR(500),
    ULTIMA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- Insertar registro inicial de federación si no existe
INSERT IGNORE INTO VRE_FEDERACION_INFO(ID, TITULO) VALUES (1, 'Federación Estudiantil UM');

-- ============================================
-- MÓDULO 10: VIDA EN EL CAMPUS
-- ============================================

CREATE TABLE IF NOT EXISTS VRE_AMENIDADES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    TIPO ENUM('COMEDOR','SNACK','RESIDENCIA','BIBLIOTECA','TIENDA','OTRO') DEFAULT 'OTRO',
    DESCRIPCION TEXT,
    UBICACION VARCHAR(200),
    COORDENADAS VARCHAR(100),
    HORARIOS TEXT,
    SERVICIOS TEXT,
    MENU TEXT,
    PRECIOS TEXT,
    IMAGEN_URL VARCHAR(500),
    GALERIA TEXT,
    CONTACTO VARCHAR(200),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(200),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- Insertar amenidades predefinidas
INSERT IGNORE INTO VRE_AMENIDADES(ID, NOMBRE, TIPO, ORDEN) VALUES
(1, 'Comedor Universitario', 'COMEDOR', 1),
(2, 'Snack UM', 'SNACK', 2),
(3, 'Residencias Estudiantiles', 'RESIDENCIA', 3);

-- ============================================
-- MÓDULO 11: REPOSITORIO DE FOTOGRAFÍAS PERSONALES
-- ============================================

CREATE TABLE IF NOT EXISTS VRE_ESTUDIANTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MATRICULA VARCHAR(7) UNIQUE NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CARRERA VARCHAR(200),
    SEMESTRE INT,
    EMAIL VARCHAR(200),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_matricula (MATRICULA)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VRE_REPOSITORIO_FOTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTUDIANTE INT NOT NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    TITULO VARCHAR(200),
    DESCRIPCION TEXT,
    FOTO_URL VARCHAR(500) NOT NULL,
    TIPO_FOTO ENUM('INDIVIDUAL','GRUPAL','EVENTO','ACADEMICA','OTRA') DEFAULT 'INDIVIDUAL',
    FECHA_FOTO DATE,
    TAGS TEXT COMMENT 'JSON con etiquetas de búsqueda',
    ORDEN INT DEFAULT 0,
    PRIVADA ENUM('S','N') DEFAULT 'N' COMMENT 'Si es privada solo la ve el dueño',
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_SUBIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES VRE_ESTUDIANTES(ID) ON DELETE CASCADE,
    INDEX idx_matricula (MATRICULA),
    INDEX idx_tipo (TIPO_FOTO),
    INDEX idx_fecha (FECHA_SUBIDA)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS VRE_REPOSITORIO_REFERENCIAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FOTO INT NOT NULL,
    MATRICULA_REFERENCIADA VARCHAR(7) NOT NULL,
    NOMBRE_REFERENCIADO VARCHAR(200),
    POSICION_X DECIMAL(5,2) COMMENT 'Coordenada X del tag en la foto (%)',
    POSICION_Y DECIMAL(5,2) COMMENT 'Coordenada Y del tag en la foto (%)',
    CONFIRMADO ENUM('S','N') DEFAULT 'N' COMMENT 'Si el referenciado confirmó que es él',
    FECHA_REFERENCIA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_FOTO) REFERENCES VRE_REPOSITORIO_FOTOS(ID) ON DELETE CASCADE,
    INDEX idx_matricula_ref (MATRICULA_REFERENCIADA)
) ENGINE=INNODB;

-- Insertar estudiante de ejemplo si no existe
INSERT IGNORE INTO VRE_ESTUDIANTES(MATRICULA, NOMBRE, APELLIDO, CARRERA, SEMESTRE, EMAIL) VALUES
('1220593', 'Usuario', 'Ejemplo', 'Ingeniería en Sistemas', 5, 'ejemplo@um.edu.mx');

-- ============================================
-- MÓDULO 12: CATÁLOGO DE CARGOS
-- ============================================

CREATE TABLE IF NOT EXISTS VRE_CARGOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    TIPO ENUM('FEDERACION','PULSO','GENERAL') DEFAULT 'GENERAL',
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_nombre (NOMBRE)
) ENGINE=INNODB;

-- Insertar cargos predefinidos
INSERT IGNORE INTO VRE_CARGOS(NOMBRE, DESCRIPCION, TIPO, ORDEN) VALUES
('PRESIDENTE', 'Presidente de la organización', 'FEDERACION', 1),
('VICEPRESIDENTE', 'Vicepresidente', 'FEDERACION', 2),
('SECRETARIO', 'Secretario', 'FEDERACION', 3),
('TESORERO', 'Tesorero', 'FEDERACION', 4),
('VOCAL', 'Vocal', 'FEDERACION', 5),
('DIRECTOR', 'Director General', 'PULSO', 1),
('SUBDIRECTOR', 'Subdirector', 'PULSO', 2),
('EDITOR', 'Editor', 'PULSO', 3),
('REDACTOR', 'Redactor', 'PULSO', 4),
('FOTÓGRAFO', 'Fotógrafo', 'PULSO', 5),
('DISEÑADOR', 'Diseñador', 'PULSO', 6);

-- ============================================
-- VERIFICACIÓN
-- ============================================

SELECT 'TABLAS AGREGADAS EXITOSAMENTE' as STATUS;
SELECT COUNT(*) as TOTAL_TABLAS FROM information_schema.tables WHERE table_schema = 'pruebasumadmin';

-- Verificar las tablas que se agregaron
SELECT 'TABLAS RECIÉN CREADAS:' as INFO;
SELECT TABLE_NAME FROM information_schema.tables
WHERE table_schema = 'pruebasumadmin'
AND TABLE_NAME IN (
    'VRE_ANUARIOS',
    'VRE_ANUARIOS_FOTOS_ESTUDIANTES',
    'VRE_ANUARIOS_LIKES',
    'VRE_PULSO_EQUIPOS',
    'VRE_ENTREGA_ANUARIO',
    'VRE_FEDERACION_MIEMBROS',
    'VRE_FEDERACION_INFO',
    'VRE_AMENIDADES',
    'VRE_ESTUDIANTES',
    'VRE_REPOSITORIO_FOTOS',
    'VRE_REPOSITORIO_REFERENCIAS',
    'VRE_CARGOS'
)
ORDER BY TABLE_NAME;
