-- ============================================
-- SISTEMA VRE - VIDA ESTUDIANTIL
-- Universidad de Montemorelos
-- Script de instalación completa - VERSIÓN INTEGRADA
-- Fecha: Noviembre 2025
-- ============================================

-- Eliminar base de datos si existe y crear nueva
DROP DATABASE IF EXISTS pruebasumadmin;
CREATE DATABASE IF NOT EXISTS pruebasumadmin CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pruebasumadmin;

-- ============================================
-- TABLAS BASE DEL SISTEMA
-- ============================================

-- Tabla de categorías de usuarios (roles)
CREATE TABLE SYSTEM_CAT_USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(300),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;

-- Insertar roles del sistema
INSERT INTO SYSTEM_CAT_USUARIOS(ID, NOMBRE, DESCRIPCION) VALUES
(1, 'SUPERUSUARIO', 'Acceso total al sistema'),
(2, 'ADMINISTRADOR', 'Administrador con permisos amplios'),
(3, 'EDITOR_INVOLUCRATE', 'Editor de módulo Involúcrate (Clubes, Ministerios, Deportes)'),
(4, 'EDITOR_EVENTOS', 'Editor de eventos y multimedia'),
(5, 'EDITOR_ANUARIOS', 'Editor de anuarios y fotografías'),
(6, 'EDITOR_CONTENIDO', 'Editor general de contenido'),
(7, 'VISUALIZADOR', 'Solo puede ver información, sin editar'),
(8, 'DIRECTOR_CLUB', 'Director de club estudiantil'),
(11, 'DIRECTOR_MINISTERIO', 'Director de ministerio');

-- Tabla de usuarios
CREATE TABLE SYSTEM_USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    PASS VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(200),
    ID_CAT INT,
    ID_CLUB_ASIGNADO INT DEFAULT NULL,
    ID_MINISTERIO_ASIGNADO INT DEFAULT NULL,
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    TOKEN VARCHAR(50),
    ULTIMO_ACCESO DATETIME,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CAT) REFERENCES SYSTEM_CAT_USUARIOS(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = INNODB;

-- Insertar usuarios por defecto
INSERT INTO SYSTEM_USUARIOS(NOMBRE, PASS, EMAIL, ID_CAT) VALUES
('Suriel', MD5('1234'), 'suriel@um.edu.mx', 1),
('admin', MD5('hikari_1950'), 'admin@um.edu.mx', 2);

-- Tabla de archivos subidos
CREATE TABLE SYSTEM_UPLOADS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(300),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    URL VARCHAR(1000)
) ENGINE = INNODB;

-- ============================================
-- SISTEMA DE PERMISOS GRANULARES
-- ============================================

-- Tabla de módulos del sistema
CREATE TABLE SYSTEM_MODULOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    SLUG VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(300),
    ICONO VARCHAR(50),
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S'
) ENGINE = INNODB;

-- Insertar módulos principales
INSERT INTO SYSTEM_MODULOS(NOMBRE, SLUG, DESCRIPCION, ICONO, ORDEN) VALUES
('Dashboard', 'dashboard', 'Panel principal de administración', 'home', 1),
('Usuarios', 'usuarios', 'Gestión de usuarios y roles', 'user', 2),
('Anuarios', 'anuarios', 'Gestión de anuarios institucionales', 'book', 3),
('Pulso UM', 'pulso', 'Gestión de equipo Pulso y entregas', 'users', 4),
('Federación', 'federacion', 'Gestión de federación estudiantil', 'award', 5),
('Clubes', 'clubes', 'Gestión de clubes estudiantiles', 'star', 6),
('Ministerios', 'ministerios', 'Gestión de ministerios', 'heart', 7),
('Deportes', 'deportes', 'Gestión de deportes y actividades', 'activity', 8),
('Ligas', 'ligas', 'Gestión de ligas deportivas', 'trophy', 9),
('Instalaciones', 'instalaciones', 'Gestión de instalaciones deportivas', 'map-pin', 10),
('Co-Curriculares', 'cocurriculares', 'Gestión de servicios co-curriculares', 'briefcase', 11),
('Eventos', 'eventos', 'Gestión de eventos y multimedia', 'calendar', 12),
('Banners', 'banners', 'Gestión de banners informativos', 'image', 13),
('Vida Campus', 'vida-campus', 'Gestión de amenidades del campus', 'coffee', 14),
('Repositorio de Fotos', 'repositorio', 'Repositorio personal de fotografías vinculadas a matrícula', 'camera', 15),
('Galería', 'galeria', 'Gestión centralizada de imágenes', 'image', 16);

-- Tabla de permisos
CREATE TABLE SYSTEM_PERMISOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    SLUG VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(300)
) ENGINE = INNODB;

-- Insertar permisos CRUD
INSERT INTO SYSTEM_PERMISOS(NOMBRE, SLUG, DESCRIPCION) VALUES
('Ver', 'ver', 'Permiso para visualizar información'),
('Crear', 'crear', 'Permiso para crear nuevos registros'),
('Editar', 'editar', 'Permiso para modificar registros existentes'),
('Eliminar', 'eliminar', 'Permiso para borrar registros'),
('Administrar', 'administrar', 'Permiso total sobre el módulo');

-- Tabla de relación: Rol - Módulo - Permisos
CREATE TABLE SYSTEM_ROL_MODULO_PERMISOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ROL INT NOT NULL,
    ID_MODULO INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES SYSTEM_CAT_USUARIOS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_MODULO) REFERENCES SYSTEM_MODULOS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PERMISO) REFERENCES SYSTEM_PERMISOS(ID) ON DELETE CASCADE,
    UNIQUE KEY unique_rol_modulo_permiso (ID_ROL, ID_MODULO, ID_PERMISO)
) ENGINE = INNODB;

-- Asignar permisos al SUPERUSUARIO (acceso total a todos los módulos)
INSERT INTO SYSTEM_ROL_MODULO_PERMISOS(ID_ROL, ID_MODULO, ID_PERMISO)
SELECT 1, m.ID, 5 FROM SYSTEM_MODULOS m;

-- Asignar permisos al ADMINISTRADOR (ver, crear, editar en todos los módulos)
INSERT INTO SYSTEM_ROL_MODULO_PERMISOS(ID_ROL, ID_MODULO, ID_PERMISO)
SELECT 2, m.ID, p.ID FROM SYSTEM_MODULOS m, SYSTEM_PERMISOS p WHERE p.SLUG IN ('ver','crear','editar');

-- Asignar permisos a EDITOR_INVOLUCRATE (módulos: clubes, ministerios, deportes, instalaciones, cocurriculares)
INSERT INTO SYSTEM_ROL_MODULO_PERMISOS(ID_ROL, ID_MODULO, ID_PERMISO)
SELECT 3, m.ID, p.ID FROM SYSTEM_MODULOS m, SYSTEM_PERMISOS p
WHERE m.SLUG IN ('clubes','ministerios','deportes','instalaciones','cocurriculares')
AND p.SLUG IN ('ver','crear','editar','eliminar');

-- Tabla de auditoría
CREATE TABLE SYSTEM_AUDITORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    MODULO VARCHAR(100),
    ACCION VARCHAR(100),
    DESCRIPCION TEXT,
    IP VARCHAR(50),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL
) ENGINE = INNODB;

-- ============================================
-- SISTEMA DE GALERÍA CENTRALIZADA
-- ============================================

CREATE TABLE VRE_GALERIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MODULO VARCHAR(50) NOT NULL COMMENT 'clubes, ministerios, deportes, ligas, eventos, banners, anuarios, pulso, federacion',
    ID_REGISTRO INT NOT NULL COMMENT 'ID del registro en la tabla correspondiente',
    TITULO VARCHAR(200),
    URL_IMAGEN VARCHAR(500) NOT NULL,
    TIPO ENUM('principal', 'galeria', 'banner', 'evento', 'miembro', 'portada') DEFAULT 'galeria',
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    SUBIDO_POR INT,
    FECHA_SUBIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SUBIDO_POR) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_modulo_registro (MODULO, ID_REGISTRO),
    INDEX idx_tipo (TIPO)
) ENGINE = INNODB;

-- ============================================
-- MÓDULO 1: ANUARIOS
-- ============================================

CREATE TABLE VRE_ANUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL,
    ANIO YEAR NOT NULL,
    DESCRIPCION TEXT,
    DECADA INT,
    ES_CONMEMORATIVO ENUM('S','N') DEFAULT 'N',
    RAZON_CONMEMORATIVA VARCHAR(300),
    IMAGEN_PORTADA VARCHAR(500),
    PDF_URL VARCHAR(500),
    TOTAL_PAGINAS INT DEFAULT 0,
    FOTOGRAFOS TEXT,
    CONTRIBUYENTES TEXT,
    LIKES INT DEFAULT 0,
    VISTAS INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO_CREADOR INT,
    FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_anio (ANIO),
    INDEX idx_decada (DECADA)
) ENGINE=INNODB;

CREATE TABLE VRE_ANUARIOS_FOTOS_ESTUDIANTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ANUARIO INT,
    MATRICULA VARCHAR(50) NOT NULL,
    NOMBRE_ESTUDIANTE VARCHAR(200),
    CARRERA VARCHAR(100),
    FACULTAD VARCHAR(100),
    FOTO_URL VARCHAR(500),
    ANIO YEAR,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FOREIGN KEY (ID_ANUARIO) REFERENCES VRE_ANUARIOS(ID) ON DELETE CASCADE,
    INDEX idx_matricula (MATRICULA)
) ENGINE=INNODB;

CREATE TABLE VRE_ANUARIOS_LIKES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ANUARIO INT NOT NULL,
    ID_USUARIO INT,
    MATRICULA VARCHAR(50),
    IP VARCHAR(50),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ANUARIO) REFERENCES VRE_ANUARIOS(ID) ON DELETE CASCADE,
    UNIQUE KEY unique_like (ID_ANUARIO, ID_USUARIO, MATRICULA, IP)
) ENGINE=INNODB;

-- ============================================
-- MÓDULO 2: PULSO UM
-- ============================================

CREATE TABLE VRE_PULSO_EQUIPOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    CARGO VARCHAR(100) NOT NULL,
    ANIO YEAR NOT NULL,
    PERIODO VARCHAR(50),
    FOTO_URL VARCHAR(500),
    BIO TEXT,
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE VRE_ENTREGA_ANUARIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ANIO YEAR UNIQUE NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_ENTREGA DATE,
    HORA_INICIO TIME,
    HORA_FIN TIME,
    LUGAR VARCHAR(200),
    INSTRUCCIONES TEXT,
    REQUISITOS TEXT,
    CONTACTO VARCHAR(200),
    IMAGEN_URL VARCHAR(500),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- ============================================
-- MÓDULO 3: FEDERACIÓN ESTUDIANTIL
-- ============================================

CREATE TABLE VRE_FEDERACION_MIEMBROS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    PUESTO VARCHAR(100) NOT NULL,
    ANIO YEAR NOT NULL,
    MATRICULA VARCHAR(50),
    CARRERA VARCHAR(100),
    FOTO_URL VARCHAR(500),
    BIO TEXT,
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(20),
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE VRE_FEDERACION_INFO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200),
    CONTENIDO_QUE_ES TEXT,
    CONTENIDO_ELECCION TEXT,
    CONTENIDO_ACTIVIDADES TEXT,
    CONTENIDO_PARA_QUE_SIRVE TEXT,
    VIDEO_URL VARCHAR(500),
    IMAGEN_PRINCIPAL VARCHAR(500),
    ULTIMA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- Insertar registro inicial de federación
INSERT INTO VRE_FEDERACION_INFO(TITULO) VALUES ('Federación Estudiantil UM');

-- ============================================
-- MÓDULO 4: CLUBES ESTUDIANTILES (VERSIÓN INTEGRADA)
-- ============================================

CREATE TABLE VRE_CLUBES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    OBJETIVO TEXT,
    REQUISITOS TEXT,
    BENEFICIOS TEXT,
    HORARIO VARCHAR(100),
    DIA_REUNION VARCHAR(50),
    LUGAR VARCHAR(200),
    CUPO_MAXIMO INT,
    CUPO_ACTUAL INT DEFAULT 0,
    RESPONSABLE_NOMBRE VARCHAR(200),
    RESPONSABLE_CONTACTO VARCHAR(200),
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(50),
    ID_DIRECTOR_USUARIO INT,
    REDES_SOCIALES JSON,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DIRECTOR_USUARIO) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_activo (ACTIVO)
) ENGINE = INNODB;

CREATE TABLE VRE_DIRECTIVA_CLUBES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLUB INT NOT NULL,
    DIRECTOR_NOMBRE VARCHAR(200),
    DIRECTOR_EMAIL VARCHAR(200),
    DIRECTOR_TELEFONO VARCHAR(50),
    DIRECTOR_FOTO VARCHAR(500),
    SUBDIRECTOR_NOMBRE VARCHAR(200),
    SUBDIRECTOR_EMAIL VARCHAR(200),
    SUBDIRECTOR_TELEFONO VARCHAR(50),
    SUBDIRECTOR_FOTO VARCHAR(500),
    SECRETARIO_NOMBRE VARCHAR(200),
    SECRETARIO_EMAIL VARCHAR(200),
    SECRETARIO_TELEFONO VARCHAR(50),
    SECRETARIO_FOTO VARCHAR(500),
    TESORERO_NOMBRE VARCHAR(200),
    TESORERO_EMAIL VARCHAR(200),
    TESORERO_TELEFONO VARCHAR(50),
    TESORERO_FOTO VARCHAR(500),
    CAPELLAN_NOMBRE VARCHAR(200),
    CAPELLAN_EMAIL VARCHAR(200),
    CAPELLAN_TELEFONO VARCHAR(50),
    CAPELLAN_FOTO VARCHAR(500),
    CONSEJERO_GENERAL_NOMBRE VARCHAR(200),
    CONSEJERO_GENERAL_EMAIL VARCHAR(200),
    CONSEJERO_GENERAL_TELEFONO VARCHAR(50),
    CONSEJERO_GENERAL_FOTO VARCHAR(500),
    LOGISTICA_NOMBRE VARCHAR(200),
    LOGISTICA_EMAIL VARCHAR(200),
    LOGISTICA_TELEFONO VARCHAR(50),
    LOGISTICA_FOTO VARCHAR(500),
    MEDIA_NOMBRE VARCHAR(200),
    MEDIA_EMAIL VARCHAR(200),
    MEDIA_TELEFONO VARCHAR(50),
    MEDIA_FOTO VARCHAR(500),
    ESTADO ENUM('activo','inactivo') DEFAULT 'activo',
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLUB) REFERENCES VRE_CLUBES(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- MÓDULO 5: MINISTERIOS (VERSIÓN INTEGRADA)
-- ============================================

CREATE TABLE VRE_MINISTERIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    OBJETIVO TEXT,
    REQUISITOS TEXT,
    BENEFICIOS TEXT,
    HORARIO VARCHAR(100),
    DIA_REUNION VARCHAR(50),
    LUGAR VARCHAR(200),
    CUPO_MAXIMO INT,
    CUPO_ACTUAL INT DEFAULT 0,
    TELEFONO VARCHAR(50),
    ID_DIRECTOR_USUARIO INT,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DIRECTOR_USUARIO) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_activo (ACTIVO)
) ENGINE = INNODB;

CREATE TABLE VRE_DIRECTIVA_MINISTERIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_MINISTERIO INT NOT NULL,
    DIRECTOR_NOMBRE VARCHAR(200),
    DIRECTOR_EMAIL VARCHAR(200),
    DIRECTOR_TELEFONO VARCHAR(50),
    DIRECTOR_FOTO VARCHAR(500),
    SUBDIRECTOR_NOMBRE VARCHAR(200),
    SUBDIRECTOR_EMAIL VARCHAR(200),
    SUBDIRECTOR_TELEFONO VARCHAR(50),
    SUBDIRECTOR_FOTO VARCHAR(500),
    SECRETARIO_NOMBRE VARCHAR(200),
    SECRETARIO_EMAIL VARCHAR(200),
    SECRETARIO_TELEFONO VARCHAR(50),
    SECRETARIO_FOTO VARCHAR(500),
    TESORERO_NOMBRE VARCHAR(200),
    TESORERO_EMAIL VARCHAR(200),
    TESORERO_TELEFONO VARCHAR(50),
    TESORERO_FOTO VARCHAR(500),
    CAPELLAN_NOMBRE VARCHAR(200),
    CAPELLAN_EMAIL VARCHAR(200),
    CAPELLAN_TELEFONO VARCHAR(50),
    CAPELLAN_FOTO VARCHAR(500),
    CONSEJERO_GENERAL_NOMBRE VARCHAR(200),
    CONSEJERO_GENERAL_EMAIL VARCHAR(200),
    CONSEJERO_GENERAL_TELEFONO VARCHAR(50),
    CONSEJERO_GENERAL_FOTO VARCHAR(500),
    LOGISTICA_NOMBRE VARCHAR(200),
    LOGISTICA_EMAIL VARCHAR(200),
    LOGISTICA_TELEFONO VARCHAR(50),
    LOGISTICA_FOTO VARCHAR(500),
    MEDIA_NOMBRE VARCHAR(200),
    MEDIA_EMAIL VARCHAR(200),
    MEDIA_TELEFONO VARCHAR(50),
    MEDIA_FOTO VARCHAR(500),
    ESTADO ENUM('activo','inactivo') DEFAULT 'activo',
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_MINISTERIO) REFERENCES VRE_MINISTERIOS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- MÓDULO 6: DEPORTES Y LIGAS (VERSIÓN INTEGRADA)
-- ============================================

CREATE TABLE VRE_DEPORTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    INDEX idx_activo (ACTIVO)
) ENGINE = INNODB;

-- Insertar deportes básicos
INSERT INTO VRE_DEPORTES(NOMBRE, DESCRIPCION, ORDEN) VALUES
('Futbol', 'Fútbol soccer', 1),
('Voleibol', 'Voleibol mixto y por género', 2),
('Basketball', 'Baloncesto', 3);

CREATE TABLE VRE_LIGAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEPORTE INT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    FECHA_INICIO DATE,
    DESCRIPCION TEXT,
    REQUISITOS TEXT,
    RESPONSABLE_NOMBRE VARCHAR(200),
    RESPONSABLE_CONTACTO VARCHAR(200),
    FOTO_RESPONSABLE VARCHAR(500),
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(50),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ESTADO ENUM('EN_PREPARACION','EN_CURSO','PAUSADO','CANCELADO') DEFAULT 'EN_PREPARACION',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DEPORTE) REFERENCES VRE_DEPORTES(ID) ON DELETE CASCADE,
    INDEX idx_activo (ACTIVO)
) ENGINE = INNODB;

CREATE TABLE VRE_DEPORTES_ACTIVIDADES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIGA INT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA DATE,
    HORA TIME,
    LUGAR VARCHAR(200),
    TIPO ENUM('PARTIDO','ENTRENAMIENTO','REUNION','OTRO') DEFAULT 'PARTIDO',
    ESTADO ENUM('PROGRAMADO','EN_CURSO','FINALIZADO','CANCELADO') DEFAULT 'PROGRAMADO',
    FOREIGN KEY (ID_LIGA) REFERENCES VRE_LIGAS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

CREATE TABLE VRE_INSTALACIONES_DEPORTIVAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    TIPO VARCHAR(100),
    CAPACIDAD INT,
    DESCRIPCION TEXT,
    UBICACION VARCHAR(300),
    HORARIO TEXT,
    ACTIVO ENUM('S','N') DEFAULT 'S'
) ENGINE = INNODB;

-- ============================================
-- MÓDULO 7: CO-CURRICULARES
-- ============================================

CREATE TABLE VRE_SERVICIOS_COCURRICULARES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    SLUG VARCHAR(200) UNIQUE NOT NULL,
    CATEGORIA ENUM('EMPRENDIMIENTO','MINISTERIO','VOLUNTARIADO','ACADEMICO','OTRO') DEFAULT 'OTRO',
    DESCRIPCION TEXT,
    OBJETIVO TEXT,
    BENEFICIOS TEXT,
    REQUISITOS TEXT,
    COMO_PARTICIPAR TEXT,
    HORARIO VARCHAR(200),
    LUGAR VARCHAR(200),
    RESPONSABLE_NOMBRE VARCHAR(200),
    RESPONSABLE_CONTACTO VARCHAR(200),
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(20),
    SITIO_WEB VARCHAR(300),
    REDES_SOCIALES TEXT,
    IMAGEN_URL VARCHAR(500),
    GALERIA TEXT,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- Insertar servicios co-curriculares predefinidos
INSERT INTO VRE_SERVICIOS_COCURRICULARES(NOMBRE, SLUG, CATEGORIA, ORDEN) VALUES
('Universidad del Mañana', 'universidad-manana', 'ACADEMICO', 1),
('Ministerio Juvenil', 'ministerio-juvenil', 'MINISTERIO', 2),
('Ministerios Musicales', 'ministerios-musicales', 'MINISTERIO', 3),
('Ministerios Instrumentales', 'ministerios-instrumentales', 'MINISTERIO', 4),
('Emprendum', 'emprendum', 'EMPRENDIMIENTO', 5),
('Enactus', 'enactus', 'EMPRENDIMIENTO', 6),
('Mentes en Misión', 'mentes-en-mision', 'VOLUNTARIADO', 7),
('Becarios', 'becarios', 'ACADEMICO', 8);

-- ============================================
-- MÓDULO 8: EVENTOS (VERSIÓN INTEGRADA)
-- ============================================

CREATE TABLE VRE_EVENTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA DATE,
    HORA TIME,
    LUGAR VARCHAR(200),
    CATEGORIA VARCHAR(100),
    ORGANIZADOR VARCHAR(200),
    CUPO_MAXIMO INT,
    REQUIERE_INSCRIPCION ENUM('S','N') DEFAULT 'N',
    ACTIVO ENUM('S','N') DEFAULT 'S',
    DESTACADO ENUM('S','N') DEFAULT 'N',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_fecha (FECHA)
) ENGINE = INNODB;

CREATE TABLE VRE_EVENTOS_ENLACES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO INT NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    URL VARCHAR(500) NOT NULL,
    TIPO ENUM('video','imagen','documento','enlace') DEFAULT 'enlace',
    ORDEN INT DEFAULT 0,
    FOREIGN KEY (ID_EVENTO) REFERENCES VRE_EVENTOS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- MÓDULO 9: BANNERS (VERSIÓN INTEGRADA)
-- ============================================

CREATE TABLE VRE_BANNERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    IMAGEN_URL VARCHAR(500),
    ENLACE VARCHAR(500),
    TIPO ENUM('EVENTO','INFORMATIVO','URGENTE','PROMOCIONAL') DEFAULT 'INFORMATIVO',
    UBICACION ENUM('HOME','EVENTOS','CLUBES','GENERAL') DEFAULT 'GENERAL',
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_activo_fechas (ACTIVO, FECHA_INICIO, FECHA_FIN)
) ENGINE = INNODB;

-- ============================================
-- MÓDULO 10: VIDA EN EL CAMPUS
-- ============================================

CREATE TABLE VRE_AMENIDADES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    TIPO ENUM('COMEDOR','SNACK','RESIDENCIA','BIBLIOTECA','TIENDA','OTRO') DEFAULT 'OTRO',
    DESCRIPCION TEXT,
    UBICACION VARCHAR(200),
    COORDENADAS VARCHAR(100),
    HORARIOS TEXT,
    SERVICIOS TEXT,
    MENU TEXT,
    PRECIOS TEXT,
    IMAGEN_URL VARCHAR(500),
    GALERIA TEXT,
    CONTACTO VARCHAR(200),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(200),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

-- Insertar amenidades predefinidas
INSERT INTO VRE_AMENIDADES(NOMBRE, TIPO, ORDEN) VALUES
('Comedor Universitario', 'COMEDOR', 1),
('Snack UM', 'SNACK', 2),
('Residencias Estudiantiles', 'RESIDENCIA', 3);

-- ============================================
-- MÓDULO 11: REPOSITORIO DE FOTOGRAFÍAS PERSONALES
-- ============================================

-- Tabla de estudiantes con datos de matrícula
CREATE TABLE VRE_ESTUDIANTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MATRICULA VARCHAR(7) UNIQUE NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CARRERA VARCHAR(200),
    SEMESTRE INT,
    EMAIL VARCHAR(200),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_matricula (MATRICULA)
) ENGINE=INNODB;

-- Tabla de fotografías personales vinculadas a matrícula
CREATE TABLE VRE_REPOSITORIO_FOTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ESTUDIANTE INT NOT NULL,
    MATRICULA VARCHAR(7) NOT NULL,
    TITULO VARCHAR(200),
    DESCRIPCION TEXT,
    FOTO_URL VARCHAR(500) NOT NULL,
    TIPO_FOTO ENUM('INDIVIDUAL','GRUPAL','EVENTO','ACADEMICA','OTRA') DEFAULT 'INDIVIDUAL',
    FECHA_FOTO DATE,
    TAGS TEXT COMMENT 'JSON con etiquetas de búsqueda',
    ORDEN INT DEFAULT 0,
    PRIVADA ENUM('S','N') DEFAULT 'N' COMMENT 'Si es privada solo la ve el dueño',
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_SUBIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ESTUDIANTE) REFERENCES VRE_ESTUDIANTES(ID) ON DELETE CASCADE,
    INDEX idx_matricula (MATRICULA),
    INDEX idx_tipo (TIPO_FOTO),
    INDEX idx_fecha (FECHA_SUBIDA)
) ENGINE=INNODB;

-- Tabla para referencias de alumnos en fotos grupales
CREATE TABLE VRE_REPOSITORIO_REFERENCIAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_FOTO INT NOT NULL,
    MATRICULA_REFERENCIADA VARCHAR(7) NOT NULL,
    NOMBRE_REFERENCIADO VARCHAR(200),
    POSICION_X DECIMAL(5,2) COMMENT 'Coordenada X del tag en la foto (%)',
    POSICION_Y DECIMAL(5,2) COMMENT 'Coordenada Y del tag en la foto (%)',
    CONFIRMADO ENUM('S','N') DEFAULT 'N' COMMENT 'Si el referenciado confirmó que es él',
    FECHA_REFERENCIA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_FOTO) REFERENCES VRE_REPOSITORIO_FOTOS(ID) ON DELETE CASCADE,
    INDEX idx_matricula_ref (MATRICULA_REFERENCIADA)
) ENGINE=INNODB;

-- Insertar estudiante de ejemplo (matrícula 1220593)
INSERT INTO VRE_ESTUDIANTES(MATRICULA, NOMBRE, APELLIDO, CARRERA, SEMESTRE, EMAIL) VALUES
('1220593', 'Usuario', 'Ejemplo', 'Ingeniería en Sistemas', 5, 'ejemplo@um.edu.mx');

-- ============================================
-- MÓDULO 12: CATÁLOGO DE CARGOS
-- ============================================

CREATE TABLE VRE_CARGOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    TIPO ENUM('FEDERACION','PULSO','GENERAL') DEFAULT 'GENERAL',
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_nombre (NOMBRE)
) ENGINE=INNODB;

-- Insertar cargos predefinidos
INSERT INTO VRE_CARGOS(NOMBRE, DESCRIPCION, TIPO, ORDEN) VALUES
('PRESIDENTE', 'Presidente de la organización', 'FEDERACION', 1),
('VICEPRESIDENTE', 'Vicepresidente', 'FEDERACION', 2),
('SECRETARIO', 'Secretario', 'FEDERACION', 3),
('TESORERO', 'Tesorero', 'FEDERACION', 4),
('VOCAL', 'Vocal', 'FEDERACION', 5),
('DIRECTOR', 'Director General', 'PULSO', 1),
('SUBDIRECTOR', 'Subdirector', 'PULSO', 2),
('EDITOR', 'Editor', 'PULSO', 3),
('REDACTOR', 'Redactor', 'PULSO', 4),
('FOTÓGRAFO', 'Fotógrafo', 'PULSO', 5),
('DISEÑADOR', 'Diseñador', 'PULSO', 6);

-- ============================================
-- TABLA DE EJEMPLO (MANTENER COMPATIBILIDAD)
-- ============================================

CREATE TABLE EXAMPLE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200),
    CORREO VARCHAR(100),
    OBSERVACIONES VARCHAR(200)
) ENGINE = INNODB;

-- ============================================
-- ÍNDICES ADICIONALES PARA OPTIMIZACIÓN
-- ============================================

-- Índices para mejorar rendimiento
ALTER TABLE SYSTEM_USUARIOS ADD INDEX idx_email (EMAIL);
ALTER TABLE SYSTEM_USUARIOS ADD INDEX idx_activo (ACTIVO);

-- ============================================
-- FIN DE LA INSTALACIÓN
-- ============================================

SELECT 'INSTALACIÓN COMPLETADA - VERSIÓN INTEGRADA' as STATUS;
SELECT 'Incluye mejoras del compañero: VRE_GALERIA, VRE_DIRECTIVA_*, VRE_LIGAS, estructura optimizada' as MEJORAS;
SELECT 'Mantiene todos tus módulos: Anuarios, Pulso, Federación, Repositorio, Amenidades' as MODULOS_ACTIVOS;
SELECT COUNT(*) as TOTAL_TABLAS FROM information_schema.tables WHERE table_schema = 'pruebasumadmin';
