-- ============================================
-- MODIFICAR TABLA EXISTENTE PARA REPOSITORIO
-- ============================================
-- Este script agrega campos a la tabla existente
-- para que funcione como repositorio personal
-- ============================================

USE pruebasumadmin;

-- Hacer ID_ANUARIO opcional (permitir NULL)
ALTER TABLE VRE_ANUARIOS_FOTOS_ESTUDIANTES
MODIFY COLUMN ID_ANUARIO INT NULL;

-- Agregar campos adicionales para repositorio personal
ALTER TABLE VRE_ANUARIOS_FOTOS_ESTUDIANTES
ADD COLUMN IF NOT EXISTS TITULO VARCHAR(200) AFTER FOTO_URL,
ADD COLUMN IF NOT EXISTS DESCRIPCION TEXT AFTER TITULO,
ADD COLUMN IF NOT EXISTS TIPO_FOTO ENUM('INDIVIDUAL','GRUPAL','EVENTO','ACADEMICA','ANUARIO','OTRA') DEFAULT 'ANUARIO' AFTER DESCRIPCION,
ADD COLUMN IF NOT EXISTS FECHA_FOTO DATE AFTER TIPO_FOTO,
ADD COLUMN IF NOT EXISTS PRIVADA ENUM('S','N') DEFAULT 'N' AFTER FECHA_FOTO,
ADD COLUMN IF NOT EXISTS FECHA_SUBIDA DATETIME DEFAULT CURRENT_TIMESTAMP AFTER PRIVADA,
ADD COLUMN IF NOT EXISTS SEMESTRE INT AFTER CARRERA;

-- Agregar índice para mejorar búsquedas
ALTER TABLE VRE_ANUARIOS_FOTOS_ESTUDIANTES
ADD INDEX IF NOT EXISTS idx_tipo_foto (TIPO_FOTO);

SELECT '✅ TABLA MODIFICADA CORRECTAMENTE' as STATUS;
SELECT 'Ahora VRE_ANUARIOS_FOTOS_ESTUDIANTES puede usarse para anuarios Y repositorio personal' as INFO;
