-- ============================================
-- SISTEMA VRE - VIDA ESTUDIANTIL
-- Universidad de Montemorelos
-- Script de Instalación Limpio - Versión Final
-- Fecha: Noviembre 2025
-- ============================================

-- Eliminar base de datos si existe y crear nueva
DROP DATABASE IF EXISTS pruebasumadmin;
CREATE DATABASE IF NOT EXISTS pruebasumadmin CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pruebasumadmin;

-- ============================================
-- TABLAS BASE DEL SISTEMA
-- ============================================

-- Tabla de categorías de usuarios (roles)
CREATE TABLE SYSTEM_CAT_USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(300),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;

-- Insertar roles del sistema
INSERT INTO SYSTEM_CAT_USUARIOS(ID, NOMBRE, DESCRIPCION) VALUES
(1, 'SUPERUSUARIO', 'Acceso total al sistema'),
(2, 'ADMINISTRADOR', 'Administrador con permisos amplios'),
(3, 'EDITOR_INVOLUCRATE', 'Editor de módulo Involúcrate (Clubes, Ministerios, Deportes)'),
(4, 'EDITOR_EVENTOS', 'Editor de eventos y multimedia'),
(5, 'VISUALIZADOR', 'Solo puede ver información, sin editar'),
(8, 'DIRECTOR_CLUB', 'Director de club estudiantil'),
(11, 'DIRECTOR_MINISTERIO', 'Director de ministerio');

-- Tabla de usuarios
CREATE TABLE SYSTEM_USUARIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    PASS VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(200),
    ID_CAT INT,
    ID_CLUB_ASIGNADO INT DEFAULT NULL,
    ID_MINISTERIO_ASIGNADO INT DEFAULT NULL,
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    TOKEN VARCHAR(50),
    ULTIMO_ACCESO DATETIME,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CAT) REFERENCES SYSTEM_CAT_USUARIOS(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = INNODB;

-- Insertar usuarios por defecto
INSERT INTO SYSTEM_USUARIOS(NOMBRE, PASS, EMAIL, ID_CAT) VALUES
('Suriel', MD5('1234'), 'suriel@um.edu.mx', 1),
('admin', MD5('hikari_1950'), 'admin@um.edu.mx', 2);

-- Tabla de archivos subidos
CREATE TABLE SYSTEM_UPLOADS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(300),
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    URL VARCHAR(1000)
) ENGINE = INNODB;

-- ============================================
-- SISTEMA DE PERMISOS GRANULARES
-- ============================================

-- Tabla de módulos del sistema
CREATE TABLE SYSTEM_MODULOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    SLUG VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(300),
    ICONO VARCHAR(50),
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S'
) ENGINE = INNODB;

-- Insertar módulos principales
INSERT INTO SYSTEM_MODULOS(NOMBRE, SLUG, DESCRIPCION, ICONO, ORDEN) VALUES
('Dashboard', 'dashboard', 'Panel principal de administración', 'home', 1),
('Usuarios', 'usuarios', 'Gestión de usuarios y roles', 'user', 2),
('Clubes', 'clubes', 'Gestión de clubes estudiantiles', 'star', 6),
('Ministerios', 'ministerios', 'Gestión de ministerios', 'heart', 7),
('Deportes', 'deportes', 'Gestión de deportes', 'activity', 8),
('Ligas', 'ligas', 'Gestión de ligas deportivas', 'trophy', 9),
('Instalaciones', 'instalaciones', 'Gestión de instalaciones deportivas', 'building', 10),
('Co-Curriculares', 'cocurriculares', 'Gestión de servicios co-curriculares', 'graduation', 11),
('Eventos', 'eventos', 'Gestión de eventos y multimedia', 'calendar', 12),
('Banners', 'banners', 'Gestión de banners informativos', 'layout', 13),
('Galería', 'galeria', 'Gestión centralizada de imágenes', 'image', 14);

-- Tabla de permisos
CREATE TABLE SYSTEM_PERMISOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    SLUG VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(300)
) ENGINE = INNODB;

-- Insertar permisos estándar
INSERT INTO SYSTEM_PERMISOS(NOMBRE, SLUG, DESCRIPCION) VALUES
('Ver', 'ver', 'Permiso para visualizar información'),
('Crear', 'crear', 'Permiso para crear nuevos registros'),
('Editar', 'editar', 'Permiso para modificar registros existentes'),
('Eliminar', 'eliminar', 'Permiso para eliminar registros');

-- Tabla de relación rol-módulo-permisos
CREATE TABLE SYSTEM_ROL_MODULO_PERMISOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ROL INT NOT NULL,
    ID_MODULO INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES SYSTEM_CAT_USUARIOS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_MODULO) REFERENCES SYSTEM_MODULOS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PERMISO) REFERENCES SYSTEM_PERMISOS(ID) ON DELETE CASCADE,
    UNIQUE KEY unique_permission (ID_ROL, ID_MODULO, ID_PERMISO)
) ENGINE = INNODB;

-- Asignar todos los permisos a SUPERUSUARIO (rol 1)
INSERT INTO SYSTEM_ROL_MODULO_PERMISOS (ID_ROL, ID_MODULO, ID_PERMISO)
SELECT 1, m.ID, p.ID
FROM SYSTEM_MODULOS m
CROSS JOIN SYSTEM_PERMISOS p;

-- Asignar todos los permisos a ADMINISTRADOR (rol 2)
INSERT INTO SYSTEM_ROL_MODULO_PERMISOS (ID_ROL, ID_MODULO, ID_PERMISO)
SELECT 2, m.ID, p.ID
FROM SYSTEM_MODULOS m
CROSS JOIN SYSTEM_PERMISOS p;

-- Tabla de auditoría
CREATE TABLE SYSTEM_AUDITORIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    MODULO VARCHAR(100),
    ACCION VARCHAR(100),
    DESCRIPCION TEXT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    IP VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL
) ENGINE = INNODB;

-- ============================================
-- SISTEMA DE GALERÍA CENTRALIZADA
-- ============================================

CREATE TABLE VRE_GALERIA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MODULO VARCHAR(50) NOT NULL COMMENT 'clubes, ministerios, deportes, ligas, eventos, banners',
    ID_REGISTRO INT NOT NULL COMMENT 'ID del registro en la tabla correspondiente',
    TITULO VARCHAR(200),
    URL_IMAGEN VARCHAR(500) NOT NULL,
    TIPO ENUM('principal', 'galeria', 'banner', 'evento') DEFAULT 'galeria',
    ORDEN INT DEFAULT 0,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    SUBIDO_POR INT,
    FECHA_SUBIDA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SUBIDO_POR) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL,
    INDEX idx_modulo_registro (MODULO, ID_REGISTRO),
    INDEX idx_tipo (TIPO)
) ENGINE = INNODB;

-- ============================================
-- MÓDULO: CLUBES ESTUDIANTILES
-- ============================================

CREATE TABLE VRE_CLUBES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    OBJETIVO TEXT,
    REQUISITOS TEXT,
    BENEFICIOS TEXT,
    HORARIO VARCHAR(100),
    DIA_REUNION VARCHAR(50),
    LUGAR VARCHAR(200),
    CUPO_MAXIMO INT,
    CUPO_ACTUAL INT DEFAULT 0,
    RESPONSABLE_NOMBRE VARCHAR(200),
    RESPONSABLE_CONTACTO VARCHAR(200),
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(50),
    ID_DIRECTOR_USUARIO INT,
    REDES_SOCIALES JSON,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DIRECTOR_USUARIO) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL
) ENGINE = INNODB;

CREATE TABLE VRE_DIRECTIVA_CLUBES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLUB INT NOT NULL,
    DIRECTOR_NOMBRE VARCHAR(200),
    DIRECTOR_EMAIL VARCHAR(200),
    DIRECTOR_TELEFONO VARCHAR(50),
    DIRECTOR_FOTO VARCHAR(500),
    SUBDIRECTOR_NOMBRE VARCHAR(200),
    SUBDIRECTOR_EMAIL VARCHAR(200),
    SUBDIRECTOR_TELEFONO VARCHAR(50),
    SUBDIRECTOR_FOTO VARCHAR(500),
    SECRETARIO_NOMBRE VARCHAR(200),
    SECRETARIO_EMAIL VARCHAR(200),
    SECRETARIO_TELEFONO VARCHAR(50),
    SECRETARIO_FOTO VARCHAR(500),
    TESORERO_NOMBRE VARCHAR(200),
    TESORERO_EMAIL VARCHAR(200),
    TESORERO_TELEFONO VARCHAR(50),
    TESORERO_FOTO VARCHAR(500),
    CAPELLAN_NOMBRE VARCHAR(200),
    CAPELLAN_EMAIL VARCHAR(200),
    CAPELLAN_TELEFONO VARCHAR(50),
    CAPELLAN_FOTO VARCHAR(500),
    CONSEJERO_GENERAL_NOMBRE VARCHAR(200),
    CONSEJERO_GENERAL_EMAIL VARCHAR(200),
    CONSEJERO_GENERAL_TELEFONO VARCHAR(50),
    CONSEJERO_GENERAL_FOTO VARCHAR(500),
    LOGISTICA_NOMBRE VARCHAR(200),
    LOGISTICA_EMAIL VARCHAR(200),
    LOGISTICA_TELEFONO VARCHAR(50),
    LOGISTICA_FOTO VARCHAR(500),
    MEDIA_NOMBRE VARCHAR(200),
    MEDIA_EMAIL VARCHAR(200),
    MEDIA_TELEFONO VARCHAR(50),
    MEDIA_FOTO VARCHAR(500),
    ESTADO ENUM('activo','inactivo') DEFAULT 'activo',
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLUB) REFERENCES VRE_CLUBES(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- MÓDULO: MINISTERIOS
-- ============================================

CREATE TABLE VRE_MINISTERIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    OBJETIVO TEXT,
    REQUISITOS TEXT,
    BENEFICIOS TEXT,
    HORARIO VARCHAR(100),
    DIA_REUNION VARCHAR(50),
    LUGAR VARCHAR(200),
    CUPO_MAXIMO INT,
    CUPO_ACTUAL INT DEFAULT 0,
    TELEFONO VARCHAR(50),
    ID_DIRECTOR_USUARIO INT,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DIRECTOR_USUARIO) REFERENCES SYSTEM_USUARIOS(ID) ON DELETE SET NULL
) ENGINE = INNODB;

CREATE TABLE VRE_DIRECTIVA_MINISTERIOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_MINISTERIO INT NOT NULL,
    DIRECTOR_NOMBRE VARCHAR(200),
    DIRECTOR_EMAIL VARCHAR(200),
    DIRECTOR_TELEFONO VARCHAR(50),
    DIRECTOR_FOTO VARCHAR(500),
    SUBDIRECTOR_NOMBRE VARCHAR(200),
    SUBDIRECTOR_EMAIL VARCHAR(200),
    SUBDIRECTOR_TELEFONO VARCHAR(50),
    SUBDIRECTOR_FOTO VARCHAR(500),
    SECRETARIO_NOMBRE VARCHAR(200),
    SECRETARIO_EMAIL VARCHAR(200),
    SECRETARIO_TELEFONO VARCHAR(50),
    SECRETARIO_FOTO VARCHAR(500),
    TESORERO_NOMBRE VARCHAR(200),
    TESORERO_EMAIL VARCHAR(200),
    TESORERO_TELEFONO VARCHAR(50),
    TESORERO_FOTO VARCHAR(500),
    CAPELLAN_NOMBRE VARCHAR(200),
    CAPELLAN_EMAIL VARCHAR(200),
    CAPELLAN_TELEFONO VARCHAR(50),
    CAPELLAN_FOTO VARCHAR(500),
    CONSEJERO_GENERAL_NOMBRE VARCHAR(200),
    CONSEJERO_GENERAL_EMAIL VARCHAR(200),
    CONSEJERO_GENERAL_TELEFONO VARCHAR(50),
    CONSEJERO_GENERAL_FOTO VARCHAR(500),
    LOGISTICA_NOMBRE VARCHAR(200),
    LOGISTICA_EMAIL VARCHAR(200),
    LOGISTICA_TELEFONO VARCHAR(50),
    LOGISTICA_FOTO VARCHAR(500),
    MEDIA_NOMBRE VARCHAR(200),
    MEDIA_EMAIL VARCHAR(200),
    MEDIA_TELEFONO VARCHAR(50),
    MEDIA_FOTO VARCHAR(500),
    ESTADO ENUM('activo','inactivo') DEFAULT 'activo',
    FECHA_ACTUALIZACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_MINISTERIO) REFERENCES VRE_MINISTERIOS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- MÓDULO: DEPORTES Y LIGAS
-- ============================================

CREATE TABLE VRE_DEPORTES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0
) ENGINE = INNODB;

-- Insertar deportes básicos
INSERT INTO VRE_DEPORTES(NOMBRE, DESCRIPCION, ORDEN) VALUES
('Futbol', 'Fútbol soccer', 1),
('Voleibol', 'Voleibol mixto y por género', 2),
('Basketball', 'Baloncesto', 3);

CREATE TABLE VRE_LIGAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEPORTE INT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    FECHA_INICIO DATE,
    DESCRIPCION TEXT,
    REQUISITOS TEXT,
    RESPONSABLE_NOMBRE VARCHAR(200),
    RESPONSABLE_CONTACTO VARCHAR(200),
    FOTO_RESPONSABLE VARCHAR(500),
    EMAIL VARCHAR(200),
    TELEFONO VARCHAR(50),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ESTADO ENUM('EN_PREPARACION','EN_CURSO','PAUSADO','CANCELADO') DEFAULT 'EN_PREPARACION',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DEPORTE) REFERENCES VRE_DEPORTES(ID) ON DELETE CASCADE
) ENGINE = INNODB;

CREATE TABLE VRE_DEPORTES_ACTIVIDADES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIGA INT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA DATE,
    HORA TIME,
    LUGAR VARCHAR(200),
    TIPO ENUM('PARTIDO','ENTRENAMIENTO','REUNION','OTRO') DEFAULT 'PARTIDO',
    ESTADO ENUM('PROGRAMADO','EN_CURSO','FINALIZADO','CANCELADO') DEFAULT 'PROGRAMADO',
    FOREIGN KEY (ID_LIGA) REFERENCES VRE_LIGAS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

CREATE TABLE VRE_INSTALACIONES_DEPORTIVAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    TIPO VARCHAR(100),
    CAPACIDAD INT,
    DESCRIPCION TEXT,
    UBICACION VARCHAR(300),
    HORARIO TEXT,
    ACTIVO ENUM('S','N') DEFAULT 'S'
) ENGINE = INNODB;

-- ============================================
-- MÓDULO: CO-CURRICULARES
-- ============================================

CREATE TABLE VRE_COCURRICULARES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    CATEGORIA VARCHAR(100),
    RESPONSABLE VARCHAR(200),
    CONTACTO VARCHAR(200),
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0
) ENGINE = INNODB;

-- ============================================
-- MÓDULO: EVENTOS
-- ============================================

CREATE TABLE VRE_EVENTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    FECHA DATE,
    HORA TIME,
    LUGAR VARCHAR(200),
    CATEGORIA VARCHAR(100),
    ORGANIZADOR VARCHAR(200),
    CUPO_MAXIMO INT,
    REQUIERE_INSCRIPCION ENUM('S','N') DEFAULT 'N',
    ACTIVO ENUM('S','N') DEFAULT 'S',
    DESTACADO ENUM('S','N') DEFAULT 'N',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;

CREATE TABLE VRE_EVENTOS_ENLACES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_EVENTO INT NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    URL VARCHAR(500) NOT NULL,
    TIPO ENUM('video','imagen','documento','enlace') DEFAULT 'enlace',
    ORDEN INT DEFAULT 0,
    FOREIGN KEY (ID_EVENTO) REFERENCES VRE_EVENTOS(ID) ON DELETE CASCADE
) ENGINE = INNODB;

-- ============================================
-- MÓDULO: BANNERS
-- ============================================

CREATE TABLE VRE_BANNERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    IMAGEN_URL VARCHAR(500),
    ENLACE VARCHAR(500),
    TIPO ENUM('EVENTO','INFORMATIVO','URGENTE','PROMOCIONAL') DEFAULT 'INFORMATIVO',
    UBICACION ENUM('HOME','EVENTOS','CLUBES','GENERAL') DEFAULT 'GENERAL',
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    ACTIVO ENUM('S','N') DEFAULT 'S',
    ORDEN INT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB;

-- ============================================
-- ÍNDICES Y OPTIMIZACIONES
-- ============================================

-- Índices para mejorar rendimiento
ALTER TABLE SYSTEM_USUARIOS ADD INDEX idx_email (EMAIL);
ALTER TABLE SYSTEM_USUARIOS ADD INDEX idx_activo (ACTIVO);
ALTER TABLE VRE_CLUBES ADD INDEX idx_activo (ACTIVO);
ALTER TABLE VRE_MINISTERIOS ADD INDEX idx_activo (ACTIVO);
ALTER TABLE VRE_DEPORTES ADD INDEX idx_activo (ACTIVO);
ALTER TABLE VRE_LIGAS ADD INDEX idx_activo (ACTIVO);
ALTER TABLE VRE_EVENTOS ADD INDEX idx_fecha (FECHA);
ALTER TABLE VRE_BANNERS ADD INDEX idx_activo_fechas (ACTIVO, FECHA_INICIO, FECHA_FIN);

-- ============================================
-- SCRIPT COMPLETADO
-- ============================================
-- Este script incluye SOLO las tablas necesarias
-- para los módulos implementados del Sistema VRE
-- Imágenes gestionadas centralizadamente en VRE_GALERIA
-- ============================================
