-- Script para verificar la estructura actual de las tablas
USE pruebasumadmin;

SELECT 'ESTRUCTURA DE VRE_COCURRICULARES:' AS INFO;
DESCRIBE VRE_COCURRICULARES;

SELECT 'ESTRUCTURA DE VRE_INSTALACIONES_DEPORTIVAS:' AS INFO;
DESCRIBE VRE_INSTALACIONES_DEPORTIVAS;

SELECT 'DATOS ACTUALES EN VRE_COCURRICULARES:' AS INFO;
SELECT * FROM VRE_COCURRICULARES LIMIT 5;

SELECT 'DATOS ACTUALES EN VRE_INSTALACIONES_DEPORTIVAS:' AS INFO;
SELECT * FROM VRE_INSTALACIONES_DEPORTIVAS LIMIT 5;
